server:
  port: 8081
spring:
  # ???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiyan2?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: gfacljz001028

# mybatis?????
mybatis:
  # mapper????
  mapper-locations: classpath:mapper/*.xml



